config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: { sessions: 'admins/sessions', passwords: 'admins/passwords' }, skip: :registrations

  namespace :admin do
  	root 'celebrities#index'
  	resources :celebrities, except: :destroy  do
      get 'wikipedia', on: :collection
      put 'status', on: :member
      resources :testimonials, shallow: true
      resources :events, shallow: true
      resources :videos, shallow: true, except: [:show]
    end
    resources :organizations, except: :destroy  do
      put 'status', on: :member
    end
    resources :clients, except: :destroy do
      put 'status', on: :member
      resources :testimonials, shallow: true
    end
    resources :services, except: :destroy do
      put 'status', on: :member
    end
    resources :booking_topics, except: :destroy do
      put 'status', on: :member
    end
    resources :booking_requests, only: [:index, :show] do
      put 'status', on: :member
    end
    resources :sites, except: :destroy do
      resources :photographs, shallow: true
      member do
        put 'featured'
        put 'status'
      end
    end
    resources :categories, except: :destroy do
      put 'status', on: :member
    end
  end

  namespace :front, path: '' do
    root 'home#index'
    resources :celebrities, only: [:index, :show]
    resources :events, only: [:index]
    resources :services, only: [:index]
    resources :clients, only: [:index]
  end
end

app/models/event.rb
class Event < ApplicationRecord

  include SortableConcern, PictureConcern, SitesConcern

  belongs_to :celebrity
  has_many :event_services, dependent: :destroy
  has_many :categories, through: :celebrity
  has_many :services, through: :event_services
  has_many :celebrity_categories, through: :celebrity

  accepts_nested_attributes_for :event_services, allow_destroy: true

  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/default.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  validates_presence_of :title, :body
  validates :image_url, url: { allow_blank: true }
  validates :title, length: { maximum: 170 }
  validates :body, length: { maximum: 2000}
  validates :event_services, length: { minimum: 1 }
  validate :validate_unique_event_services

  attr_accessor :delete_photo

  before_validation { photo.clear if delete_photo == '1' }

  # ---------- CLASSES METHODS -----------------
  def self.filter_by_term(term)
    left_joins(event_services: :service).where("LOWER(events.title) LIKE ? OR LOWER(services.name) LIKE ?", "%#{term.downcase}%", "%#{term.downcase}%").group(:id)
  end
  # ---------- END CLASSES METHODS -------------

  private

  def validate_unique_event_services
    validate_uniqueness_of_in_memory(event_services, [:event_id, :service_id], 'Duplicate services')
  end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < AdminController

  before_action :set_celebrity, only: %i[index new create]
  before_action :set_event, only: %i[show edit update destroy]

  helper_method :sort_column, :sort_direction

  def index
    @events = @celebrity.events.includes(:services,:categories).order(sort_column + ' ' + sort_direction)
    @events = @events.filter_by_term(params[:term]) if params[:term].present?
    @events = @events.paginate(page: params[:page], per_page: 50)

    respond_to do |f|
      f.html {render :index }
      f.js { render :index, layout: false }
    end
  end

  def show
  end

  def new
    @event = @celebrity.events.new
    @event.event_services.build
    load_services
  end

  def create
    @event = @celebrity.events.new(event_params)
    if @event.save
      redirect_to admin_celebrity_events_path(@celebrity), notice: "Successfully created"
    else
      render partial: 'errors/errors', locals: { resource: @event }
    end
  end

  def edit
    load_services
  end

  def update
    if @event.update(event_params)
      redirect_to admin_celebrity_events_path(@event.celebrity), notice: "Successfully updated"
    else
      render partial: 'errors/errors', locals: { resource: @event }
    end
  end

  def destroy
    @event.destroy
    render :destroy, layout: false
  end

  private

  def set_celebrity
    @celebrity = Celebrity.find(params[:celebrity_id])
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end

  def sort_column
    Event.column_names.include?(params[:sort]) ? params[:sort] : "created_at"
  end

  def event_params
    params.require(:event).permit(:title, :body, :image_url, :photo, :delete_photo,
                                    event_services_attributes: [:id, :service_id, :_destroy])
  end

end

app/controllers/front/events_controller.rb
class Front::EventsController < FrontController

  def index
  end
end

app/views/admin/events/_event.haml
%tr{id: "#{dom_id event}"}
  %td= event.title
  %td
    .two-lines= event.services.sort_by(&:name).map(&:name).join(', ').html_safe
  %td
    .two-lines= event.categories.sort_by(&:name).map(&:name).join(', ').html_safe
  %td= event.created_at.to_date
  %td
    = link_to admin_event_path(event), class: 'black-text' do
      %i.material-icons visibility
    %span &nbsp;
    = link_to edit_admin_event_path(event), class: 'black-text' do
      %i.material-icons edit
    %span &nbsp;
    %a{href: "#", 'data-url': "#{admin_event_path(event)}", 'data-confirmation-text': "#{event.title}",'data-option-text': 'delete', class: 'open-modal-confirmation red-text'}
      %i.material-icons delete

app/views/admin/events/_form.haml
= nested_form_for [:admin,@celebrity,@event], multipart: true, remote: true do |f|

  #errors.red-text.center.bold.hidden An error occured

  .row
    .input-field.col.s12
      = f.text_field :title,'data-length': '170'
      = f.label :title
      %small.red-text#title_error

  .row
    .col.s12
      = label_tag :services, 'Services'
      = f.link_to_add :event_services, class: 'deep-purple-text text-accent-4' ,:data => { :target => "#event_services" } do
        %i.material-icons{style: "vertical-align: middle"} add
      %p.no-margin
        %small.red-text#event_services_error
        %small.red-text#base_error
    .col.s12#event_services
      = f.fields_for :event_services do |sc_form|
        .row
          .col.s10.m6.no-padding
            = sc_form.select :service_id, options_from_collection_for_select(@services,'id','name',sc_form.object.service_id)
          .col.s2.m2.little-top-space
            = sc_form.link_to_remove class: 'red-text left' do
              %i.material-icons.small delete

  .row
    .col.s12
      = label_tag :image, 'Image'
  .row
    .col.s12
      %ul.tabs
        %li.tab.col.s6
          %a{href: "#url", class: 'custom-color-text bold'} Paste URL
        %li.tab.col.s6
          %a{href: "#upload", class: 'custom-color-text bold'} Upload File

    #url.col.s12
      .top-space
        .input-field
          = f.text_field :image_url
          = f.label :image_url, 'Image URL', class: 'active'
          %small.red-text#image_url_error

    #upload.col.s12
      .row
        .col.s12.no-padding
          - if @event.photo.present?
            = image_tag @event.photo.url, class: 'image_to_upload top-space', height: 300, width: 300
            = f.check_box :delete_photo, class: 'hidden'
            %a{href: "#", class: 'red-text delete-image'}
              %i.material-icons.small delete
          - else
            %img{src: '',class: 'hidden image_to_upload top-space' }

      .col.s12.m5.no-padding
        .file-field.input-field
          .btn.deep-purple.accent-4
            %span Photo
            = f.file_field :photo, class: 'photo_upload'
          .file-path-wrapper
            %input{type: 'text', class: 'file-path validate', value: @event.photo.original_filename}

  .row
    .input-field.col.s12
      = f.text_area :body, class: 'materialize-textarea','data-length': '2000'
      = f.label :body
      %small.red-text#body_error

app/views/admin/events/_table_header.haml
%tr.pretty
  %th= sortable 'title', 'Título'
  %th Services
  %th Categories
  %th= sortable 'created_at', 'Created at'
  %th Actions

app/views/admin/events/destroy.js.erb
$("#<%= dom_id @event %>").fadeOut("slow",function(){$(this).remove()})
$("#modalConfirmation").modal('close')
Materialize.toast('Successfully deleted', 4000)

app/views/admin/events/edit.haml
.card.no-margin
  .card-content

    .row.border-collection
      %nav.white.black-text.z-depth-0
        .nav-wrapper
          .col.s12.m10
            = link_to 'Celebrities',admin_celebrities_path, class: "breadcrumb blue-text"
            = link_to @event.celebrity.name,admin_celebrity_path(@event.celebrity), class: "breadcrumb blue-text"
            = link_to 'Events',admin_celebrity_events_path(@event.celebrity), class: "breadcrumb blue-text"
            = link_to 'EDIT',edit_admin_event_path(@event), class: "breadcrumb black-text"
          .col.s12.m2.right-text
            = submit_tag 'Save', "data-disable-with": "Saving ...", class: 'deep-purple accent-4 btn', form: "edit_event_#{@event.id}"

    .row
      .col.s12
        = render 'form'

app/views/admin/events/index.haml
.fixed-action-btn.new-button
  = link_to new_admin_celebrity_event_path(@celebrity), class: "btn-floating waves-effect waves-light btn-large deep-purple accent-4 btn" do
    %i.material-icons add

.card.no-margin
  .card-content

    .row.border-collection
      %nav.white.black-text.z-depth-0
        .nav-wrapper
          .col.s12
            = link_to 'Celebrities',admin_celebrities_path, class: "breadcrumb blue-text"
            = link_to @celebrity.name,admin_celebrity_path(@celebrity), class: "breadcrumb blue-text"
            = link_to 'Events',admin_celebrity_events_path(@celebrity), class: "breadcrumb black-text"

    = form_tag admin_celebrity_events_path(@celebrity), method: :get, remote: true do
      %p.bold.medium EVENTS
      .row.no-margin
        .input-field.col.s12.no-padding.search-input
          %i.material-icons.prefix search
          = text_field_tag :term, params[:term]
          = label_tag :term, 'Search by title or service'
      .row
        .col.s12.no-padding
          = button_tag :submit, "data-disable-with": "Searching ...", class: 'btn deep-purple accent-4 right' do
            Search

    .overflow-x
      %table.centered
        %thead#table_header
          = render 'table_header'
        %tbody#events_index
          = render @events

    .top-space.center.pagination-from-table
      = will_paginate @events, renderer: MaterializePaginationCustomHelper::PaginateMaterailizeLinkRenderer


= render 'admin/shareds/modal_confirmation'

app/views/admin/events/index.js.erb
$("#events_index").html("<%= j render partial: 'event', collection: @events, as: :event %>")
$('.pagination-from-table').html('<%= j will_paginate @events, renderer: MaterializePaginationCustomHelper::PaginateMaterailizeLinkRenderer %>')
$("#table_header").html("<%= j render 'table_header' %>")

app/views/admin/events/new.haml
.card.no-margin
  .card-content

    .row.border-collection
      %nav.white.black-text.z-depth-0
        .nav-wrapper
          .col.s12.m10
            = link_to 'Celebrities',admin_celebrities_path, class: "breadcrumb blue-text"
            = link_to @celebrity.name,admin_celebrity_path(@celebrity), class: "breadcrumb blue-text"
            = link_to 'Events',admin_celebrity_events_path(@celebrity), class: "breadcrumb blue-text"
            = link_to 'ADD',new_admin_celebrity_event_path(@celebrity), class: "breadcrumb black-text"
          .col.s12.m2.right-text
            = submit_tag 'Save', "data-disable-with": "Saving ...", class: 'deep-purple accent-4 btn', form: 'new_event'

    .row
      .col.s12
        = render 'form'

app/views/admin/events/show.haml
.card.no-margin
  .card-content
    .row.border-collection
      %nav.white.black-text.z-depth-0
        .nav-wrapper
          .col.s12
            = link_to 'Celebrities',admin_celebrities_path, class: "breadcrumb blue-text"
            = link_to @event.celebrity.name,admin_celebrity_path(@event.celebrity), class: "breadcrumb blue-text"
            = link_to 'Events',admin_celebrity_events_path(@event.celebrity), class: "breadcrumb blue-text"
            = link_to 'VIEW',[:admin,@event], class: "breadcrumb black-text"

    .row
      .col.s12.m4
        %span.bold Image
      .col.s12.m8
        = print_zoom_image(@event.portrait)

    .row
      .col.s12.m4
        %span.bold Title
      .col.s12.m8
        %span= @event.title

    .row
      .col.s12.m4
        %span.bold Body
      .col.s12.m8
        %span{style: "white-space: pre-line"}= @event.body

    .row
      .col.s12.m4
        %span.bold Service
      .col.s12.m8
        %span= @event.services.sort_by(&:name).map(&:name).join(', ').html_safe

    .row
      .col.s12.m4
        %span.bold Category
      .col.s12.m8
        %span= @event.categories.sort_by(&:name).map(&:name).join(', ').html_safe