config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: { sessions: 'admins/sessions', passwords: 'admins/passwords' }, skip: :registrations

  namespace :admin do
  	root 'celebrities#index'
  	resources :celebrities, except: :destroy  do
      get 'wikipedia', on: :collection
      put 'status', on: :member
      resources :testimonials, shallow: true
      resources :events, shallow: true
      resources :videos, shallow: true, except: [:show]
    end
    resources :organizations, except: :destroy  do
      put 'status', on: :member
    end
    resources :clients, except: :destroy do
      put 'status', on: :member
      resources :testimonials, shallow: true
    end
    resources :services, except: :destroy do
      put 'status', on: :member
    end
    resources :booking_topics, except: :destroy do
      put 'status', on: :member
    end
    resources :booking_requests, only: [:index, :show] do
      put 'status', on: :member
    end
    resources :sites, except: :destroy do
      resources :photographs, shallow: true
      member do
        put 'featured'
        put 'status'
      end
    end
    resources :categories, except: :destroy do
      put 'status', on: :member
    end
  end

  namespace :front, path: '' do
    root 'home#index'
    resources :celebrities, only: [:index, :show]
    resources :events, only: [:index]
    resources :services, only: [:index]
    resources :clients, only: [:index]
  end
end

app/models/photograph.rb
class Photograph < ApplicationRecord
  include SortableConcern, PictureConcern, SitesConcern

   belongs_to :site

   enum section: [:who_we_are,:banner]

   has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/default.png"
   validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

   validates_presence_of :title, :section
   validates :image_url, url: { allow_blank: true }
   validates :title, length: { maximum: 100 }
   validates :subtitle, :url, length: { maximum: 200 }
   validate :should_have_image_url_or_photo
   validate :count_of_images_for_who_we_are, on: :create
   validate :count_of_images_for_banner, on: :create

   attr_accessor :delete_photo

   before_validation { photo.clear if delete_photo == '1' }
   before_create :clear_subtitle, on: :create

   MAX_IMAGE_PER_BANNER = 3
   MAX_IMAGE_PER_WHO_ARE = 18

   private
   def should_have_image_url_or_photo
     if !self.image_url.present? and !self.photo.present?
       errors.add(:base,'Should enter image URL or upload file')
     end
   end

   def count_of_images_for_who_we_are
     if self.section == "who_we_are" and self.site.photographs.who_we_are.count >= Photograph::MAX_IMAGE_PER_WHO_ARE
       errors.add(:base,"Images are too long(maximum is 18 photos)")
     end
   end

   def count_of_images_for_banner
     if self.section == "banner" and self.site.photographs.banner.count >= Photograph::MAX_IMAGE_PER_BANNER
       errors.add(:base,"Images are too long(maximum is 3 photos)")
     end
   end

   def clear_subtitle
     self.subtitle = nil if self.section == "who_we_are"
   end

end

app/controllers/admin/photographs_controller.rb
class Admin::PhotographsController < AdminController

  before_action :set_site, only: %i[index new create]
  before_action :set_photograph, only: %i[show edit update destroy]

  helper_method :sort_column, :sort_direction

  def index
    @photographs = @site.photographs.order(sort_column + ' ' + sort_direction).paginate(page: params[:page], per_page: 50)

    respond_to do |f|
      f.html {render :index }
      f.js { render :index, layout: false }
    end
  end

  def show
    render :show, layout: false
  end

  def new
    @photograph = Photograph.new
  end

  def create
    @photograph = @site.photographs.new(photograph_params)
    if @photograph.save(photograph_params)
      redirect_to admin_site_photographs_path(@photograph.site), notice: "Successfully updated"
    else
      render partial: 'errors/errors', locals: { resource: @photograph }
    end
  end

  def edit
  end

  def update
    if @photograph.update(photograph_params)
      redirect_to admin_site_photographs_path(@photograph.site), notice: "Successfully updated"
    else
      render partial: 'errors/errors', locals: { resource: @photograph }
    end
  end

  def destroy
    @photograph.destroy
    render :destroy, layout: false
  end

  private

  def set_site
    @site = Site.find(params[:site_id])
  end

  def set_photograph
    @photograph = Photograph.find(params[:id])
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end

  def sort_column
    Photograph.column_names.include?(params[:sort]) ? params[:sort] : 'title'
  end

  def photograph_params
    params.require(:photograph).permit(:title, :subtitle, :section, :url, :image_url, :photo, :delete_photo)
  end

end

app/helpers/photograph_helper.rb
module PhotographHelper

  def banner_remaing_amount(site)
    content_tag(:span,
    Photograph::MAX_IMAGE_PER_BANNER - site.photographs.banner.count,
    id: 'banner_count')
  end

  def who_we_are_remaing_amount(site)
    content_tag(:span,
    Photograph::MAX_IMAGE_PER_WHO_ARE - site.photographs.who_we_are.count,
    id: 'who_we_are_count')
  end

end

app/views/admin/photographs/_form.haml
= form_for [:admin,@site, @photograph], remote: true do |f|

  #errors.red-text.center.bold.hidden An error occured

  .row
    .input-field.col.s12.m6
      = f.text_field :title, 'data-length': '100'
      = f.label :title
      %small.red-text#title_error

    .input-field.col.s12.m4
      = f.select(:section, class_enum_for_select("Photograph", "section"), {prompt: "Choose an option"},{class: 'select-section'})
      = f.label :section
      %small.red-text#section_error

  .row#section_banner_fields{class: "#{'hidden' unless @photograph.banner?}"}
    .input-field.col.s12.m6
      = f.text_field :subtitle, 'data-length': '200'
      = f.label :subtitle
      %small.red-text#subtitle_error

    .input-field.col.s12.m6
      = f.text_field :url, 'data-length': '200'
      = f.label :url, 'URL'
      %small.red-text#url_error

  .row
    .col.s12
      = label_tag :image, 'Image'
      %p.no-margin
        %small.red-text#base_error

  .row
    .col.s12
      %ul.tabs
        %li.tab.col.s6
          %a{href: "#url", class: 'custom-color-text bold'} Paste URL
        %li.tab.col.s6
          %a{href: "#upload", class: 'custom-color-text bold'} Upload File

    #url.col.s12
      .top-space
        .input-field
          = f.text_field :image_url
          = f.label :image_url, 'Image URL', class: 'active'
          %small.red-text#image_url_error

    #upload.col.s12
      .row
        .col.s12.no-padding
          - if @photograph.photo.present?
            = image_tag @photograph.photo.url, class: 'image_to_upload top-space', height: 300, width: 300
            = f.check_box :delete_photo, class: 'hidden'
            %a{href: "#", class: 'red-text delete-image'}
              %i.material-icons.small delete
          - else
            %img{src: '',class: 'hidden image_to_upload top-space' }

      .col.s12.m5.no-padding
        .file-field.input-field
          .btn.deep-purple.accent-4
            %span Photo
            = f.file_field :photo, class: 'photo_upload'
          .file-path-wrapper
            %input{type: 'text', class: 'file-path validate', value: @photograph.photo.original_filename}

app/views/admin/photographs/_photograph.haml
%tr{id: "#{dom_id photograph}"}
  %td= photograph.title
  %td= photograph.subtitle.presence || '-'
  %td= photograph.section.titleize
  %td
    = link_to admin_photograph_path(photograph), remote: true, class: 'black-text' do
      %i.material-icons photo
    = link_to edit_admin_photograph_path(photograph), class: 'black-text' do
      %i.material-icons edit
    %a{href: "#", 'data-url': "#{admin_photograph_path(photograph)}", 'data-confirmation-text': "#{photograph.title}", 'data-option-text': 'delete', class: 'open-modal-confirmation red-text'}
      %i.material-icons delete

app/views/admin/photographs/_show.haml
.full-height.full-width{style: "background-image: url(#{@photograph.portrait});background-size: cover; background-repeat: no-repeat;"}
  %p.bold.medium.no-margin.white-text{style: "position: absolute; bottom: 4px; left: 9px;"}= @photograph.title.upcase

app/views/admin/photographs/_table_header.haml
%tr.pretty
  %th= sortable 'title', 'Title'
  %th= sortable 'subtitle', 'Subtitle'
  %th= sortable 'section', 'Section'
  %th Actions

app/views/admin/photographs/destroy.js.erb
$("#<%= dom_id @photograph %>").fadeOut("slow",function(){$(this).remove()})

<% if @photograph.section == 'who_we_are' %>
  remaing_amount = parseInt($("#who_we_are_count").text()) + 1
  $("#who_we_are_count").text(remaing_amount)
<% elsif @photograph.section == 'banner' %>
  remaing_amount = parseInt($("#banner_count").text()) + 1
  $("#banner_count").text(remaing_amount)
<% end %>

$("#modalConfirmation").modal('close')
Materialize.toast('Successfully deleted', 4000)

app/views/admin/photographs/edit.haml
.card.no-margin
  .card-content

    .row.border-collection
      %nav.white.black-text.z-depth-0
        .nav-wrapper
          .col.s12.m10
            = link_to 'Sites',admin_sites_path, class: "breadcrumb blue-text"
            = link_to @photograph.site.name,admin_site_photographs_path(@photograph.site), class: "breadcrumb blue-text"
            = link_to 'Photos',admin_site_photographs_path(@photograph.site), class: "breadcrumb blue-text"
            = link_to 'ADD',new_admin_site_photograph_path(@photograph.site), class: "breadcrumb black-text"
          .col.s12.m2.right-text
            = submit_tag 'Save', "data-disable-with": "Saving ...", class: 'deep-purple accent-4 btn', form: "edit_photograph_#{@photograph.id}"


    .row
      .col.s12
        = render 'form'

app/views/admin/photographs/index.haml
.fixed-action-btn.new-button
  = link_to new_admin_site_photograph_path(@site), class: "btn-floating waves-effect waves-light btn-large deep-purple accent-4 btn" do
    %i.material-icons add

.card.no-margin
  .card-content

    .row.border-collection
      %nav.white.black-text.z-depth-0
        .nav-wrapper
          .col.s12
            = link_to 'Sites',admin_sites_path, class: "breadcrumb blue-text"
            = link_to @site.name,admin_site_photographs_path(@site), class: "breadcrumb blue-text"
            = link_to 'Photos',admin_site_photographs_path(@site), class: "breadcrumb black-text"

    .row
      .col.s12.m5
        %span.bold Remaining amount of photos for banner section:
      .col.s12.m7
        = banner_remaing_amount(@site)
    .row
      .col.s12.m5
        %span.bold Remaining amount of photos for who we are section:
      .col.s12.m7
        = who_we_are_remaing_amount(@site)

    .overflow-x
      %table.centered
        %thead#table_header
          = render 'table_header'
        %tbody#photographs_index
          = render @photographs

    .top-space.center.pagination-from-table
      = will_paginate @photographs, renderer: MaterializePaginationCustomHelper::PaginateMaterailizeLinkRenderer

.modal#modalShowPhotograph{style: "width: 80%; height: 80%"}
= render 'admin/shareds/modal_confirmation'

app/views/admin/photographs/index.js.erb
$("#photographs_index").html("<%= j render partial: 'photograph', collection: @photographs, as: :photograph %>")
$('.pagination-from-table').html('<%= j will_paginate @photographs, renderer: MaterializePaginationCustomHelper::PaginateMaterailizeLinkRenderer %>')
$("#table_header").html("<%= j render 'table_header' %>")

app/views/admin/photographs/new.haml
.card.no-margin
  .card-content

    .row.border-collection
      %nav.white.black-text.z-depth-0
        .nav-wrapper
          .col.s12.m10
            = link_to 'Sites',admin_sites_path, class: "breadcrumb blue-text"
            = link_to @site.name,admin_site_photographs_path(@site), class: "breadcrumb blue-text"
            = link_to 'Photos',admin_site_photographs_path(@site), class: "breadcrumb blue-text"
            = link_to 'ADD',new_admin_site_photograph_path(@site), class: "breadcrumb black-text"
          .col.s12.m2.right-text
            = submit_tag 'Save', "data-disable-with": "Saving ...", class: 'deep-purple accent-4 btn', form: 'new_photograph'

    .row
      .col.s12
        = render 'form'

app/views/admin/photographs/show.js.erb
$("#modalShowPhotograph").html("<%= j render 'show' %>")
$("#modalShowPhotograph").modal("open")