config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: { sessions: 'admins/sessions', passwords: 'admins/passwords' }, skip: :registrations

  namespace :admin do
  	root 'celebrities#index'
  	resources :celebrities, except: :destroy  do
      get 'wikipedia', on: :collection
      put 'status', on: :member
      resources :testimonials, shallow: true
      resources :events, shallow: true
      resources :videos, shallow: true, except: [:show]
    end
    resources :organizations, except: :destroy  do
      put 'status', on: :member
    end
    resources :clients, except: :destroy do
      put 'status', on: :member
      resources :testimonials, shallow: true
    end
    resources :services, except: :destroy do
      put 'status', on: :member
    end
    resources :booking_topics, except: :destroy do
      put 'status', on: :member
    end
    resources :booking_requests, only: [:index, :show] do
      put 'status', on: :member
    end
    resources :sites, except: :destroy do
      resources :photographs, shallow: true
      member do
        put 'featured'
        put 'status'
      end
    end
    resources :categories, except: :destroy do
      put 'status', on: :member
    end
  end

  namespace :front, path: '' do
    root 'home#index'
    resources :celebrities, only: [:index, :show]
    resources :events, only: [:index]
    resources :services, only: [:index]
    resources :clients, only: [:index]
  end
end

app/controllers/front/celebrities_controller.rb
class Front::CelebritiesController < FrontController

  def index
  end
end

app/controllers/front/clients_controller.rb
class Front::ClientsController < FrontController

  def index
  end
end

app/controllers/front/events_controller.rb
class Front::EventsController < FrontController

  def index
  end
end

app/controllers/front/home_controller.rb
class Front::HomeController < FrontController

  def index
    @banner_photos = current_site.photographs.banner.limit(3)
    @who_we_are_photos = current_site.photographs.who_we_are.limit(3)
    @featured_celebrities = Celebrity.match_with_categories_of_site(current_site).active.filter_by_featured.lasted.limit(3)
  end

end

app/controllers/front/services_controller.rb
class Front::ServicesController < FrontController

  def index
  end
end

app/controllers/front_controller.rb
class FrontController < ApplicationController

  include LoadInformationConcern, AuthenticateSiteConcern

  before_action :authenticate_site

end

app/helpers/front_helper.rb
module FrontHelper

  def li_paint_tab(text, path, controller_name)
    css_class = controller.controller_name == controller_name ? 'active' : ''
    content_tag(:li, class: css_class) do
      link_to text, path
    end
  end
end

app/views/front/shareds/_navbar.haml
%nav
  .nav-wrapper.custom-color
    = image_tag current_site.logo, class: 'logo'
    = link_to 'Hire Celebrities', front_root_path, class: 'brand-logo'
    %a.button-collapse{href: '#', 'data-activates': 'mobile'}
      %i.material-icons menu
    %ul.right.hide-on-med-and-down
      = li_paint_tab('Celebrities', front_celebrities_path, 'celebrities')
      = li_paint_tab('Services', front_services_path, 'services')
      = li_paint_tab('Events', front_events_path, 'events')
      = li_paint_tab('Clients', front_clients_path, 'clients')
      = li_paint_tab('Contact', front_root_path, 'contacts')

    %ul.side-nav#mobile
      = li_paint_tab('Celebrities', front_celebrities_path, 'celebrities')
      = li_paint_tab('Services', front_services_path, 'services')
      = li_paint_tab('Events', front_events_path, 'events')
      = li_paint_tab('Clients', front_clients_path, 'clients')
      = li_paint_tab('Contact', front_root_path, 'contacts')