config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: { sessions: 'admins/sessions', passwords: 'admins/passwords' }, skip: :registrations

  namespace :admin do
  	root 'celebrities#index'
  	resources :celebrities, except: :destroy  do
      get 'wikipedia', on: :collection
      put 'status', on: :member
      resources :testimonials, shallow: true
      resources :events, shallow: true
      resources :videos, shallow: true, except: [:show]
    end
    resources :organizations, except: :destroy  do
      put 'status', on: :member
    end
    resources :clients, except: :destroy do
      put 'status', on: :member
      resources :testimonials, shallow: true
    end
    resources :services, except: :destroy do
      put 'status', on: :member
    end
    resources :booking_topics, except: :destroy do
      put 'status', on: :member
    end
    resources :booking_requests, only: [:index, :show] do
      put 'status', on: :member
    end
    resources :sites, except: :destroy do
      resources :photographs, shallow: true
      member do
        put 'featured'
        put 'status'
      end
    end
    resources :categories, except: :destroy do
      put 'status', on: :member
    end
  end

  namespace :front, path: '' do
    root 'home#index'
    resources :celebrities, only: [:index, :show]
    resources :events, only: [:index]
    resources :services, only: [:index]
    resources :clients, only: [:index]
  end
end

app/models/video.rb
class Video < ApplicationRecord

  include SortableConcern, SitesConcern

  belongs_to :celebrity
  has_many :categories, through: :celebrity

  validates_presence_of :name
  validates :url, url: { allow_blank: false }
  validate :check_if_is_youtube_url

  before_validation :set_youtube_url

  # ---------- CLASSES METHODS -----------------
  def self.filter_by_featured
    where("videos.featured = ?",true)
  end

  # ---------- END CLASSES METHODS -------------

  # ---------- INSTANCE METHODS ----------------
  # ---------- END INSTANCE METHODS ------------

  private

  def check_if_is_youtube_url
    unless self.url.include? 'youtube.com' or self.url.include? 'youtu.be'
      errors.add(:url,'is invalid YouTube URL')
    end
  end

  def set_youtube_url
    if self.url.include? 'youtube.com' and !self.url.include? 'embed'
      url_array = self.url.split '/watch?v='
      self.url = "https://youtube.com/embed/#{url_array[1]}"
    elsif self.url.include? 'youtu.be'
      url_array = self.url.split 'youtu.be/'
      self.url = "https://youtube.com/embed/#{url_array[1]}"
    end
  end

end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < AdminController

  before_action :set_celebrity, only: %i[index new create]
  before_action :set_video, only: %i[edit update destroy]

  helper_method :sort_column, :sort_direction

  def index
    @videos = @celebrity.videos.order(sort_column + ' ' + sort_direction).paginate(page: params[:page], per_page: 50)

    respond_to do |f|
      f.html {render :index }
      f.js { render :index, layout: false }
    end
  end

  def new
    @video = Video.new
  end

  def create
    @video = @celebrity.videos.new(video_params)
    if @video.save
      redirect_to admin_celebrity_videos_path(@celebrity), notice: "Successfully created"
    else
      render partial: 'errors/errors', locals: { resource: @video }
    end
  end

  def edit
  end

  def update
    if @video.update(video_params)
      redirect_to admin_celebrity_videos_path(@video.celebrity), notice: "Successfully updated"
    else
      render partial: 'errors/errors', locals: { resource: @video }
    end
  end

  def destroy
    @video.destroy
    render :destroy, layout: false
  end

  private

  def set_celebrity
    @celebrity = Celebrity.find(params[:celebrity_id])
  end

  def set_video
  	@video = Video.find(params[:id])
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def sort_column
    Video.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  def video_params
    params.require(:video).permit(:name, :featured, :url)
  end

end

app/views/admin/videos/_form.haml
= form_for [:admin,@celebrity,@video], multipart: true, remote: true do |f|

  #errors.red-text.center.bold.hidden An error occured

  .row
    .input-field.col.s12
      = f.text_field :name,'data-length': '170'
      = f.label :name
      %small.red-text#name_error

  .row
    .input-field.col.s12
      = f.text_field :url,'data-length': '170'
      = f.label :url, 'URL (YouTube)'
      %small.red-text#url_error

  .row
    .col.s12.m2
      = f.check_box :featured
      = f.label :featured, 'Featured'

app/views/admin/videos/_table_header.haml
%tr.pretty
  %th= sortable 'name', 'Name'
  %th= sortable 'featured', 'Featured'
  %th URL
  %th Actions

app/views/admin/videos/_video.haml
%tr{id: "#{dom_id video}"}
  %td= video.name
  %td= video.featured.humanize
  %td
    %a.open-video-modal{href: "#"}= video.url
  %td
    = link_to edit_admin_video_path(video), class: 'black-text' do
      %i.material-icons edit
    %span &nbsp;
    %a{href: "#", 'data-url': "#{admin_video_path(video)}", 'data-confirmation-text': "#{video.name}",'data-option-text': 'delete', class: 'open-modal-confirmation red-text'}
      %i.material-icons delete

app/views/admin/videos/destroy.js.erb
$("#<%= dom_id @video %>").fadeOut("slow",function(){$(this).remove()})
$("#modalConfirmation").modal('close')
Materialize.toast('Successfully deleted', 4000)

app/views/admin/videos/edit.haml
.card.no-margin
  .card-content

    .row.border-collection
      %nav.white.black-text.z-depth-0
        .nav-wrapper
          .col.s12.m10
            = link_to 'Celebrities',admin_celebrities_path, class: "breadcrumb blue-text"
            = link_to @video.celebrity.name, admin_celebrity_path(@video.celebrity), class: "breadcrumb blue-text"
            = link_to 'Videos',admin_celebrity_videos_path(@video.celebrity), class: "breadcrumb blue-text"
            = link_to 'EDIT',edit_admin_video_path(@video), class: "breadcrumb black-text"
          .col.s12.m2.right-text
            = submit_tag 'Save', "data-disable-with": "Saving ...", class: 'deep-purple accent-4 btn', form: "edit_video_#{@video.id}"

    .row
      .col.s12
        = render 'form'

app/views/admin/videos/index.haml
.fixed-action-btn.new-button
  = link_to new_admin_celebrity_video_path(@celebrity), class: "btn-floating waves-effect waves-light btn-large deep-purple accent-4 btn" do
    %i.material-icons add

.card.no-margin
  .card-content

    .row.border-collection
      %nav.white.black-text.z-depth-0
        .nav-wrapper
          .col.s12
            = link_to 'Celebrities',admin_celebrities_path, class: "breadcrumb blue-text"
            = link_to @celebrity.name,admin_celebrity_path(@celebrity), class: "breadcrumb blue-text"
            = link_to 'Videos',admin_celebrity_videos_path(@celebrity), class: "breadcrumb black-text"

    .overflow-x
      %table.centered
        %thead#table_header
          = render 'table_header'
        %tbody#videos_index
          = render @videos

    .top-space.center.pagination-from-table
      = will_paginate @videos, renderer: MaterializePaginationCustomHelper::PaginateMaterailizeLinkRenderer


= render 'admin/shareds/modal_confirmation'
= render 'admin/shareds/modal_show_video'

app/views/admin/videos/index.js.erb
$("#videos_index").html("<%= j render partial: 'video', collection: @videos, as: :video %>")
$('.pagination-from-table').html('<%= j will_paginate @videos, renderer: MaterializePaginationCustomHelper::PaginateMaterailizeLinkRenderer %>')
$("#table_header").html("<%= j render 'table_header' %>")

app/views/admin/videos/new.haml
.card.no-margin
  .card-content

    .row.border-collection
      %nav.white.black-text.z-depth-0
        .nav-wrapper
          .col.s12.m10
            = link_to 'Celebrities',admin_celebrities_path, class: "breadcrumb blue-text"
            = link_to @celebrity.name,admin_celebrity_videos_path(@celebrity), class: "breadcrumb blue-text"
            = link_to 'Videos',admin_celebrity_videos_path(@celebrity), class: "breadcrumb blue-text"
            = link_to 'ADD',new_admin_celebrity_video_path(@celebrity), class: "breadcrumb black-text"
          .col.s12.m2.right-text
            = submit_tag 'Save', "data-disable-with": "Saving ...", class: 'deep-purple accent-4 btn', form: 'new_video'

    .row
      .col.s12
        = render 'form'